# This workflow prepares the JavaScript and CSS modules for distribution via jsDelivr.
name: Build and Deploy to Release Branch

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Read version from version.txt
        id: version
        run: echo "VERSION=$(cat version.txt)" >> $GITHUB_ENV

      - name: Create versioned directory and root directory for latest build
        run: |
          mkdir -p dist/${{ env.VERSION }}
          mkdir -p dist/latest

      - name: Copy assets to versioned and root directories
        run: |
          # Copy all .js, .css, and the new app.html file
          for file in *.js *.css app.html; do
            if [ -f "$file" ]; then
              cp "$file" "dist/${{ env.VERSION }}/"
              cp "$file" "dist/latest/"
            fi
          done
          echo "Copied assets to dist/${{ env.VERSION }}/ and dist/latest/"

      - name: Commit 'dist' folder to 'release' branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: release
          FOLDER: dist
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Build: ({sha}) {msg}"

